q2_final<-merge(q2_dataset1_agg_copy,net_mean_sd,by=c("provider_type","nppes_provider_state"))
library(readxl)
library(readXl)
install.packages("readxl")
library(readXl)
library(readxl)
library(data.table)
dataset1<-fread("Dataset1/Medicare_Physician_and_Other_Supplier_NPI_Aggregate_CY2014.txt")
dataset2<-read_excel("DataSet2/HH_PUF_Provider_2014.xlsx")
dataset3<-fread("DataSet3/PartD_Prescriber_PUF_NPI_Drug_14.txt")
dataset4<-read_excel("DataSet4/16_0921_Hospice_PUF_Provider_Table_Suppressed.xlsx")
dataset5<-fread("DataSet5/Medicare_Referring_Provider_DMEPOS_PUF_CY2014.txt")
head(dataset1)
dataset1[which(dataset1$average_Medicare_allowed_amt>dataset1$average_submitted_chrg_amt),]
head(dataset3)
library(XLConnect)
dataset2_S<-loadWorkbook("DataSet2/HH_PUF_Provider_2014.xlsx")
dataset2<-readWorksheet(dataset2_S,3,header = TRUE)
dataset2_S<-loadWorkbook("DataSet2/HH_PUF_Provider_2014.xlsx")
dataset2<-read_excel("DataSet2/HH_PUF_Provider_2014.xlsx",3)
dataset4<-read_excel("DataSet4/16_0921_Hospice_PUF_Provider_Table_Suppressed.xlsx",3)
head(dataset3)
head(dataset5)
dataset1[which(dataset1$average_Medicare_allowed_amt>dataset1$average_submitted_chrg_amt),]
colnames(dataset1)
unique(dataset1$nppes_provider_country)
dim(dataset1[which(dataset1$nppes_provider_country=='US'),])
dim(dataset1)
colnames(dataset4)
colnames(dataset1)
colnames(dataset1_agg)
View(dataset1)
View(dataset1)
dataset1<- dataset1[-1,]
View(dataset1)
View(dataset1)
unique(dataset1$provider_type)
library(aggregate)
dataset1_agg_copy<-dataset1_agg[-grep("Suppliers",dataset1_agg$provider_type),]
dataset1_agg_copy<-data.frame(dataset1_agg_copy)
dataset1<-dataset1[-grep("Suppliers",dataset1$provider_type),]
dataset1<-data.frame(dataset1)
dataset1$average_submitted_chrg_amt<-dataset1$total_submitted_chrg_amt/dataset1$total_services
dataset1_state_city_provider_avg_expen<-aggregate(average_submitted_chrg_amt~nppes_provider_state+nppes_provider_city+provider_type,dataset1,mean)
View(dataset1_state_city_provider_avg_expen)
View(dataset1_state_city_provider_avg_expen)
dataset1_agg_copy$avg_per_service<- dataset1_agg_copy$total_submitted_chrg_amt/dataset1_agg_copy$total_services
dataset1_us_avg_provider_type<-aggregate(avg_per_service~provider_type,dataset1_agg_copy,sd)
dataset1_us_avg_provider_type_mean<-aggregate(avg_per_service~provider_type,dataset1_agg_copy,mean)
colnames(dataset1_us_avg_provider_type)[2]="per_service_sd"
colnames(dataset1_us_avg_provider_type_mean)[2]="per_service_mean"
us_per_service_mean_sd<-merge(dataset1_us_avg_provider_type_mean,dataset1_us_avg_provider_type)
dataset1_state_avg_provider_type<-aggregate(avg_per_service~provider_type+nppes_provider_state,dataset1_agg_copy,mean)
dataset1_state_sd_provider_type<-aggregate(avg_per_service~provider_type+nppes_provider_state,dataset1_agg_copy,sd)
state_per_service_mean_sd<-merge(dataset1_state_sd_provider_type,dataset1_state_avg_provider_type,by=c("provider_type","nppes_provider_state"))
state_per_servce_mean_sd$sd_per_service_state<-as.integer(state_per_servce_mean_sd$sd_per_service_state)
state_per_servce_mean_sd$mean_per_service_state<-as.integer(state_per_servce_mean_sd$mean_per_service_state)
colnames(us_per_service_mean_sd)[2]<-"us_mean"
colnames(us_per_service_mean_sd)[3]<-"us_sd"
net_mean_sd<-merge(us_per_service_mean_sd,state_per_servce_mean_sd,by="provider_type")
q2_dataset1_agg_copy<-dataset1_agg_copy[,c("npi","nppes_provider_last_org_name","nppes_provider_zip","nppes_provider_state","provider_type","avg_per_service")]
q2_final<-merge(q2_dataset1_agg_copy,net_mean_sd,by=c("provider_type","nppes_provider_state"))
q2_final$'mean_diff_serv_chrg%'<-ifelse(q2_final$us_mean>=q2_final$mean_per_service_state,(q2_final$avg_per_service-q2_final$us_mean)/(q2_final$us_mean)*100,(q2_final$avg_per_service-q2_final$mean_per_service_state)/(q2_final$mean_per_service_state)*100)
q2_final$too_high_serv_chrg<-ifelse(q2_final$'mean_diff_serv_chrg%'>10,1,0)
q2_final$state_used<-ifelse(q2_final$us_mean>=q2_final$mean_per_service_state,0,1)
q2_final$us_used<-ifelse(q2_final$us_mean>=q2_final$mean_per_service_state,1,0)
q1_final<-merge(dataset1_state_city_provider_avg_expen,dataset1_us_avg_provider_type_mean,by="provider_type")
colnames(q1_final_min)[3]<-"state_min_amt"
colnames(q1_final_max)[3]<-"state_max_amt"
q1_final<-merge(q1_final,q1_final_min,by=c("provider_type","nppes_provider_state"))
q1_final<-merge(q1_final,q1_final_max,by=c("provider_type","nppes_provider_state"))
q1_most_expensive<-q1_final%>% select(provider_type,nppes_provider_state,average_submitted_chrg_amt,per_service_mean,state_min_amt,state_max_amt) %>% group_by(nppes_provider_state)%>%filter(dense_rank(desc(average_submitted_chrg_amt))==1)
